In [22]:
import os
import pandas as pd
import numpy as np
import glob
import json

In [2]:
from pandas.io.json import json_normalize
import warnings

warnings.filterwarnings("ignore")

In [3]:
flag = 1
for file in glob.glob("*-tweets.json"):
    df = pd.read_json(file, lines = True)
    if flag == 1:
        cols = df.columns
        df_users = pd.DataFrame(columns = cols)
        flag = 0
    else:
        df_users = pd.concat([df_users,df])

In [5]:
#normalize user object
users = json_normalize(df_users['user'])
users.drop(['description', 'linkTcourl'], axis=1, inplace=True)
users.rename(columns={'id':'userId', 'url':'profileUrl'}, inplace=True)
users.head(2)

,_type,username,displayname,userId,rawDescription,descriptionUrls,verified,created,followersCount,friendsCount,statusesCount,favouritesCount,listedCount,mediaCount,location,protected,linkUrl,profileImageUrl,profileBannerUrl,profileUrl
0,snscrape.modules.twitter.User,btfmrises,ً,1225094973948878853,i am not a troll btw,[],False,2020-02-05T16:33:04+00:00,17,14,329,1113,0,68,"s/h, 25, white",False,None,https://pbs.twimg.com/profile_images/134189462...,https://pbs.twimg.com/profile_banners/12250949...,https://twitter.com/btfmrises
1,snscrape.modules.twitter.User,btfmrises,ً,1225094973948878853,i am not a troll btw,[],False,2020-02-05T16:33:04+00:00,17,14,329,1113,0,68,"s/h, 25, white",False,None,https://pbs.twimg.com/profile_images/134189462...,https://pbs.twimg.com/profile_banners/12250949...,https://twitter.com/btfmrises

In [6]:
#drop duplicates
users = pd.DataFrame(users)
users.drop_duplicates(subset=['userId'], inplace=True)
users.head(5)

,_type,username,displayname,userId,rawDescription,descriptionUrls,verified,created,followersCount,friendsCount,statusesCount,favouritesCount,listedCount,mediaCount,location,protected,linkUrl,profileImageUrl,profileBannerUrl,profileUrl
0,snscrape.modules.twitter.User,btfmrises,ً,1225094973948878853,i am not a troll btw,[],False,2020-02-05T16:33:04+00:00,17,14,329,1113,0,68,"s/h, 25, white",False,None,https://pbs.twimg.com/profile_images/134189462...,https://pbs.twimg.com/profile_banners/12250949...,https://twitter.com/btfmrises
217,snscrape.modules.twitter.User,bisexualjb,tristan,702934687551983616,"what the actual fuck, oh my gosh how insecure ...",[],False,2016-02-25T19:14:24+00:00,171,40,81,11,0,21,exo 💟 got2,False,https://curiouscat.me/imjaebeoms,https://pbs.twimg.com/profile_images/928670687...,https://pbs.twimg.com/profile_banners/70293468...,https://twitter.com/bisexualjb
269,snscrape.modules.twitter.User,joohwangsi,save palestine🇵🇸,1368643588054118400,positive vibes only❤️,[],False,2021-03-07T19:24:05+00:00,197,266,5207,8236,0,441,exopink,False,None,https://pbs.twimg.com/profile_images/139300639...,https://pbs.twimg.com/profile_banners/13686435...,https://twitter.com/joohwangsi
4689,snscrape.modules.twitter.User,icnsgore,ateez disband,1393369710717280263,"no staneo a nadie, no rompan las bolas",[],False,2021-05-15T00:56:49+00:00,25,25,126,46,0,11,él,False,None,https://pbs.twimg.com/profile_images/139438966...,https://pbs.twimg.com/profile_banners/13933697...,https://twitter.com/icnsgore
4701,snscrape.modules.twitter.User,bbarajey,loona flop disband,1395442212062863366,...,[],False,2021-05-20T18:12:12+00:00,2,4,22,5,0,1,,False,None,https://pbs.twimg.com/profile_images/139544242...,None,https://twitter.com/bbarajey

In [7]:
users.verified.unique()

array([False])

In [8]:
user_cols = ['username', 'displayname', 'userId','rawDescription','verified','created','followersCount',
       'friendsCount', 'statusesCount', 'favouritesCount', 'listedCount',
       'mediaCount', 'location']

In [9]:
tweet_users = users[user_cols]
tweet_users.head(5)

,username,displayname,userId,rawDescription,verified,created,followersCount,friendsCount,statusesCount,favouritesCount,listedCount,mediaCount,location
0,btfmrises,ً,1225094973948878853,i am not a troll btw,False,2020-02-05T16:33:04+00:00,17,14,329,1113,0,68,"s/h, 25, white"
217,bisexualjb,tristan,702934687551983616,"what the actual fuck, oh my gosh how insecure ...",False,2016-02-25T19:14:24+00:00,171,40,81,11,0,21,exo 💟 got2
269,joohwangsi,save palestine🇵🇸,1368643588054118400,positive vibes only❤️,False,2021-03-07T19:24:05+00:00,197,266,5207,8236,0,441,exopink
4689,icnsgore,ateez disband,1393369710717280263,"no staneo a nadie, no rompan las bolas",False,2021-05-15T00:56:49+00:00,25,25,126,46,0,11,él
4701,bbarajey,loona flop disband,1395442212062863366,...,False,2021-05-20T18:12:12+00:00,2,4,22,5,0,1,

In [10]:
tweet_users.shape

(19, 13)

In [11]:
tweet_users.to_csv('snsusers_users.csv',index = False)

In [12]:
#add userid column
user_id = []
for user in df_users['user']:
    uid = user['id']
    user_id.append(uid)
df_users['userId'] = user_id

In [13]:
#clean
cols = ['date', 'renderedContent', 'id', 'userId', 'replyCount', 'retweetCount', 'likeCount', 'quoteCount', 'media', 'quotedTweet', 'mentionedUsers', 'lang']
tweets = df_users[cols]
tweets.rename(columns={'id':'tweetId'}, inplace=True)
tweets.head(5)

,date,renderedContent,tweetId,userId,replyCount,retweetCount,likeCount,quoteCount,media,quotedTweet,mentionedUsers,lang
0,2021-05-29 00:53:33+00:00,@TETEPROTECT0R he’s jinjja uwu~~😞,1398442352868462596,1225094973948878853,1,0,1,0,None,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",in
1,2021-05-28 23:54:38+00:00,@J4MAlSVU_ @yeoyxy @vminkookurz yes coz even s...,1398427525844549633,1225094973948878853,5,2,2,11,None,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",en
2,2021-05-28 22:06:12+00:00,@jnkstigmaa chan outsold https://t.co/A5jMzyqVvZ,1398400240173076481,1225094973948878853,1,0,0,1,"[{'_type': 'snscrape.modules.twitter.Photo', '...",None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",en
3,2021-05-28 22:03:53+00:00,@jnkstigmaa EXCUSE MEEEEE&amp;:):&amp;):£: i a...,1398399655533236232,1225094973948878853,1,0,0,0,None,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",en
4,2021-05-28 22:02:39+00:00,@jnkstigmaa gottem mad https://t.co/RncbakBowH,1398399345356165122,1225094973948878853,1,0,0,0,"[{'_type': 'snscrape.modules.twitter.Gif', 'th...",None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",en

In [14]:
#convert to dataframe, drop duplicates, keep only english tweets
tweets = pd.DataFrame(tweets)
tweets.drop_duplicates(subset=['tweetId'], inplace=True)
print(tweets.shape)

(7134, 12)

In [16]:
tweets.dtypes

date               datetime64[ns, UTC]
renderedContent                 object
tweetId                         object
userId                           int64
replyCount                      object
retweetCount                    object
likeCount                       object
quoteCount                      object
media                           object
quotedTweet                     object
mentionedUsers                  object
lang                            object
dtype: object

In [23]:
lang_codes = json.load( open( "language_mapping.json" ) )

In [24]:
tweets['lang'] = tweets['lang'].map(lang_codes)

In [25]:
tweets.head()

,date,renderedContent,tweetId,userId,replyCount,retweetCount,likeCount,quoteCount,media,quotedTweet,mentionedUsers,lang
0,2021-05-29 00:53:33+00:00,@TETEPROTECT0R he’s jinjja uwu~~😞,1398442352868462596,1225094973948878853,1,0,1,0,None,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",Indonesian
1,2021-05-28 23:54:38+00:00,@J4MAlSVU_ @yeoyxy @vminkookurz yes coz even s...,1398427525844549633,1225094973948878853,5,2,2,11,None,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",English
2,2021-05-28 22:06:12+00:00,@jnkstigmaa chan outsold https://t.co/A5jMzyqVvZ,1398400240173076481,1225094973948878853,1,0,0,1,"[{'_type': 'snscrape.modules.twitter.Photo', '...",None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",English
3,2021-05-28 22:03:53+00:00,@jnkstigmaa EXCUSE MEEEEE&amp;:):&amp;):£: i a...,1398399655533236232,1225094973948878853,1,0,0,0,None,None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",English
4,2021-05-28 22:02:39+00:00,@jnkstigmaa gottem mad https://t.co/RncbakBowH,1398399345356165122,1225094973948878853,1,0,0,0,"[{'_type': 'snscrape.modules.twitter.Gif', 'th...",None,"[{'_type': 'snscrape.modules.twitter.User', 'u...",English

In [26]:
#tweets.to_csv('snsusers_tweets.csv',index = False)

In [27]:
tweets = pd.read_csv('snsusers_tweets.csv')

In [29]:
tweets.lang.unique()

array(['Indonesian', 'English', nan, 'Tagalog', 'Spanish; Castilian',
       'Estonian', 'Danish', 'Haitian', 'Italian', 'Polish', 'Dutch',
       'Portuguese', 'Romanian, Moldavan', 'Lithuanian', 'French',
       'Norwegian', 'Latvian', 'German', 'Welsh', 'Swedish', 'Korean',
       'Basque', 'Turkish', 'Hindi', 'Hungarian', 'Finnish', 'Czech',
       'Slovene', 'Icelandic', 'Catalan; Valencian'], dtype=object)

In [36]:
tweets[['tweetId','lang']].groupby('lang').count().sort_values(by=['tweetId'], ascending=False)

                    tweetId
lang
English                5893
Spanish; Castilian      406
Indonesian               78
Tagalog                  65
Korean                   57
Estonian                 57
Polish                   37
Haitian                  35
Danish                   32
French                   29
Portuguese               16
German                   14
Dutch                    12
Romanian, Moldavan       12
Swedish                  11
Welsh                     6
Italian                   6
Norwegian                 5
Hungarian                 5
Slovene                   4
Finnish                   4
Basque                    4
Latvian                   3
Lithuanian                3
Czech                     3
Catalan; Valencian        2
Icelandic                 2
Turkish                   2
Hindi                     1